### ISSUE TITLE
Bug when using py2rb

### ISSUE THREAD

**Issue by javierojeda94** [naitoh/py2rb#2]
I just found your package and it seems to be a good one.

I installed it and tried to run it but I just found this error message on my terminal:

```bash
$ py2rb python.py
Traceback (most recent call last):
  File "/usr/local/bin/py2rb", line 7, in <module>
    from py2rb import main
  File "/usr/local/lib/python2.7/site-packages/py2rb/__init__.py", line 2919
    print('Try  : ' + py_path + ' -> ' + output + ' : ', end='')
                                                            ^
SyntaxError: invalid syntax
```

The contents of my `python.py` file:
```python
result=0
a,b=0,2
for x in range(1500):
    a,b=b,a+(4*b)
    if a<4000000:
        result+=a
print(result)
```

Can you help me?

**Comment by wtn** [comment]
I upgraded from Python 2.7 to Python 3.7 and ran `pip install six` and it worked.

**Comment by naitoh** [comment]
I am sorry that your reply was delayed.
py2rb.py does not support Python 2.7.
Please use Python 3.5, 3.6.
